version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app  # Mount the current directory
      - ./settlement_transactions.json:/app/settlement_transactions.json  # Mount the JSON file
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/clearsettle-ai-firebase-adminsdk-fbsvc-844f7a5e30.json
    depends_on:
      - firestore-emulator

  firestore-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    ports:
      - "8080:8080"
    command: gcloud beta emulators firestore start --host-port=0.0.0.0:8080
    environment:
      - FIRESTORE_PROJECT_ID=clearsettle-ai